### ISSUE TITLE
商品一覧ページを正常に表示させる

### ISSUE THREAD

**Issue by nsmryk** [yuka-dir/mercari-build-hackthon-team2#14]
`http://localhost:3000/` にアクセスしても商品一覧が表示されないのでその修正

- [x] Goでのコードに合わせてstructの配列で商品のリストを返す

**Comment by uukait** [comment]
ここに関して、idが情報に入っていない＆＆辞書で返ってきていないことが原因でした。

以下のように返していただけると、フロント側で受け取れます！
```
for i in range(len(items)):
            item_dict["items"].append({"id": items[i][0], "name": items[i][1], "category": items[i][2], "image_filename": items[i][3]})
    return item_dict
```

**Comment by nsmryk** [comment]
ありがとうございます！
name, categoryは表示されたのですが画像が表示されないのでまだ改善入りそうです😭

**Comment by nsmryk** [comment]
一応修正して表示されるようになったのですが、ItemList.tsxの方を変更してしまっています。
