### ISSUE TITLE
商品一覧ページのデザインを修正する

### ISSUE THREAD

**Issue by uukait** [yuka-dir/mercari-build-hackthon-team2#21]
現状
- 商品画像の背景が白、かつ、ページの背景も白
- 商品がページいっぱいに並ぶ
→ トリミングあり・なし並べても違いが分かりずらい

**Comment by nsmryk** [comment]
- 背景を薄いグレーか黒に変える
- 商品をリサイズして同じ大きさに変える
と違いが分かりやすそうですね
